# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2612a36a1eb0404f69150dfc6777357274f345adfebef26ed237ebfd9fa44ad864c1995c456e57d23443452d23adfc753838f80eb8aea8dab3528b962cac158

test:
  secret_key_base: 6d321b090fb8e6c756498a4704830280b1123795032acd54c90e5b56ba358e99f8516fbd55e7040de33f9db33797056df5247ac9a6db84a185e98f61d5566c2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
